<div class="row">
    <div class="col-md-4 stretch-card grid-margin">
        <div class="card bg-gradient-success card-img-holder text-white">
            <div class="card-body">
                <img src="images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                <h4 class="font-weight-normal mb-3">Ilość uzbrojenia
                    <i class="mdi mdi-diamond mdi-24px float-right"></i>
                </h4>
                <h2 class="mb-5"><?php echo (int)$this->products_count; ?></h2>
                <h6 class="card-text">
                <a href="<?php echo $this->url(array('controller'=>'product','action'=>'index'));?>" class="btn btn-gradient-dark btn-fw p-2">Zobacz</a>
                </h6>
            </div>
        </div>
    </div>
    <div class="col-md-4 stretch-card grid-margin">
        <div class="card bg-gradient-info card-img-holder text-white">
            <div class="card-body">
                <img src="images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                <h4 class="font-weight-normal mb-3">Dodaj
                    <i class="mdi mdi-bookmark-outline mdi-24px float-right"></i>
                </h4>
                <h2 class="mb-5">do arsenału</h2>
                <h6 class="card-text">
                    <a href="<?php echo $this->url(array('controller'=>'product','action'=>'add'));?>" class="btn btn-gradient-dark btn-fw p-2">Dodaj</a>
                </h6>
            </div>
        </div>
    </div>
</div>
