<div class="row">
	<div class="col-lg-12 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">
				<table class="table">
					<thead>
						<tr>
							<th>ID</th>
							<th>Nazwa</th>
							<th>Cena</th>
							<th>Stawka VAT</th>
							<th>Status</th>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->products as $product) : ?>
							<tr>
								<td>
									<?php echo $this->escape($product->id); ?>
								</td>
								<td>
									<?php echo $this->escape($product->name); ?>
								</td>
								<td>
									<?php echo number_format($product->price, 2, ',', '`'); ?> zł
								</td>
								<td>
									<?php echo $this->escape($product->tax); ?>%
								</td>
								<td>
									<label class="<?php echo $this->fake['status'][$product->status]['class']; ?>">
										<?php echo $this->fake['status'][$product->status]['value']; ?>
									</label>
								</td>
								<td>
									<a href="<?php echo $this->url(array('controller'=>'product','action'=>'delete', 'id'=>$product->id));?>" class="btn btn-danger p-2">Usuń</a>
								</td>
								<td>
									<a href="<?php echo $this->url(array('controller'=>'product','action'=>'edit', 'id'=>$product->id));?>" class="btn btn-success p-2">Edytuj</a>
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-12">
		<span class="d-flex align-items-center purchase-popup">
			<a href="/product/add" class="btn purchase-button">Dodaj uzbrojenie</a>
		</span>
	</div>
</div>