<div class="row">
	<div class="col-lg-12 grid-margin stretch-card">
		<div class="card">

			<div class="card-body">
				<?php if (!empty($this->search)) { ?>
				<table class="table">
					<thead>
						<tr>
							<th>Nazwa</th>
							<th>Cena</th>
							<th>Stawka VAT</th>
							<th>Status</th>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->search as $product) : ?>
							<tr>
								<td>
									<?php echo $product["_id"]; ?>
								</td>
								<td>
									<?php echo $this->escape($product['_source']['name']); ?>
								</td>
								<td>
									<?php echo number_format($product['_source']['price'], 2, ',', '`'); ?> zł
								</td>
								<td>
									<?php echo $this->escape($product['_source']['tax']); ?>%
								</td>
								<td>
									<label class="<?php echo $this->fake['status'][$product['_source']['status']]['class']; ?>">
										<?php echo $this->fake['status'][$product['_source']['status']]['value']; ?>
									</label>
								</td>
								<td>
									<a href="<?php echo $this->url(array('controller'=>'product','action'=>'edit', 'id'=>$product["_id"]));?>" class="btn btn-success p-2">Edytuj</a>
								</td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
				<?php } else { ?>
					<h1>Brak produktów o wybranym kreterium!</h1>
				<?php }?>
			</div>
		</div>
	</div>
</div>